version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: postgres_db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '5433:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  nestjs-app:
    build: .
    container_name: nestjs_app
    restart: always
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - '3000:3000'
    command: ['npm', 'run', 'start:dev']

volumes:
  pgdata:
